name: play4u
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  local_audio_scan: ^2.0.0
  audioplayers: ^6.0.0
  provider: ^6.0.0
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
